spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/greennae
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
#      show_sql: true
        format_sql: true
        open-in-view: true
        profiles:
        active: local

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: C://upload
      max-file-size: 30MB
      max-request-size: 30MB

logging:
  level:
    org.hibernate.SQL: debug

file:
  path: C:/upload/

spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
#JSP수정시 서버 재시작없이 바로 적용될 수 있게 설정 server.servlet.jsp.init-parameters.development=true

